# Generated by Django 4.2.7 on 2023-11-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categoria',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
