# Generated by Django 4.2.7 on 2023-11-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_data_review_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
